# Generated by Django 6.0.3 on 2026-04-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='design',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
