# Generated by Django 6.0.3 on 2026-04-27 21:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_cv_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='share_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
