# Generated by Django 6.0.3 on 2026-04-27 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_cv_share_expires_alter_cv_share_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='Dashboard.cv')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
